# Generated by Django 3.0.2 on 2020-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches_Pred_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('league', models.CharField(max_length=5)),
                ('MW', models.IntegerField(default=0)),
                ('HomeTeam', models.CharField(max_length=200)),
                ('AwayTeam', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=5)),
                ('prediction', models.CharField(max_length=5)),
                ('Result', models.CharField(max_length=10)),
                ('result_binary', models.IntegerField()),
                ('corrected', models.IntegerField()),
                ('proba', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Matches_Pred_Upcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('league', models.CharField(max_length=5)),
                ('MW', models.IntegerField(default=0)),
                ('HomeTeam', models.CharField(max_length=200)),
                ('AwayTeam', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=5)),
                ('prediction', models.CharField(max_length=5)),
                ('proba', models.FloatField(default=0)),
            ],
        ),
    ]
